app:
  notification_mailer: !!python/object:demoapp.models.config.NotificationMailerConfig
    from_name: "Example Blog Postmaster"
    from_address: "noreply@example.com"
    admin_name: "John Doe"
    admin_address: "doe@example.com"
    dsn: "smtp://invalid"
  db_connection_url: "sqlite:///var/blog.db"
