name: Run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create venv
        run: python -m venv .venv
      - name: Install poetry
        run: ./.venv/bin/pip install poetry
      - name: Poetry install
        run: ./.venv/bin/poetry install --no-root
      - name: Run tests
        run: ./.venv/bin/python -m unittest
